/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/nav/1/dept': RouteRecordInfo<'/nav/1/dept', '/nav/1/dept', Record<never, never>, Record<never, never>>,
    '/nav/1/emp': RouteRecordInfo<'/nav/1/emp', '/nav/1/emp', Record<never, never>, Record<never, never>>,
    '/nav/1/salgrade': RouteRecordInfo<'/nav/1/salgrade', '/nav/1/salgrade', Record<never, never>, Record<never, never>>,
    '/nav/2/mongodb': RouteRecordInfo<'/nav/2/mongodb', '/nav/2/mongodb', Record<never, never>, Record<never, never>>,
    '/nav/2/oracle': RouteRecordInfo<'/nav/2/oracle', '/nav/2/oracle', Record<never, never>, Record<never, never>>,
    '/nav/2/postgresql': RouteRecordInfo<'/nav/2/postgresql', '/nav/2/postgresql', Record<never, never>, Record<never, never>>,
  }
}
